# Build the app
# node:20.10-bookworm-slim, node:hydrogen-alpine3.19
FROM node:hydrogen-alpine3.19 as build

# info
ENV NODE_ENV=developement

# update the system
# RUN apt update -y && apt install -y openssl
RUN apk update && apk add openssl
RUN npm install -g npm

# link the global modules to the local modules
RUN ln -s /usr/local/lib/node_modules/ ./node_modules

# copy the source code
COPY . /app
RUN chmod -R 755 /app
WORKDIR /app
COPY ./.env.example.prod ./.env

# build the app
# -------------------------------------------------------
RUN npm cache clean --force
RUN rm -rf package-lock.json

# Error: Could not resolve @prisma/client despite the installation that we just tried.
# Please try to install it by hand with npm i @prisma/client and rerun npx "prisma generate" 🙏.
# Somehow not working with the prepare script, that should install it automatically.
RUN npm i @prisma/client
RUN npx prisma generate
# include dev because vite.config.ts requires modules from it
RUN npm i --include=dev
RUN npm run build:node
# -------------------------------------------------------

# Host the build files
FROM node:hydrogen-alpine3.19

# info
ENV NODE_ENV=production

# info
ENV HOST=0.0.0.0
ENV PORT=80
EXPOSE 80/tcp

# copy the build files
WORKDIR /app
COPY --from=build /app .

CMD ["node","build"]
