# https://docs.deno.com/runtime/manual/advanced/deploying_deno/google_cloud_run#create-dockerfile-and-docker-composeyml
# https://docs.deno.com/runtime/manual/references/cheatsheet
# https://pnpm.io/docker
FROM node:20-slim AS base

RUN npm install -g npm@10.5.0

COPY . /app
COPY ./.env.example.prod /app/.env
WORKDIR /app

FROM base AS prod-deps
# --production
RUN npm install --frozen-lockfile --ignore-scripts --omit=dev

FROM base AS build
RUN apt-get update -y && apt-get install -y openssl

RUN npm install @prisma/client && npx prisma generate
RUN npm install --frozen-lockfile --ignore-scripts
# RUN deno task build:deno
RUN npm run build:deno

FROM denoland/deno:debian-1.41.3 AS runtime

# COPY --from=prod-deps /app/node_modules /app/node_modules
COPY --from=build /app/build /app/

ENV NODE_ENV=production

ENV PORT=80
EXPOSE 80/tcp

ENTRYPOINT ["deno", "run", "--allow-env", "--allow-read", "--allow-net", "/app/server.js"]
