# Using the LTS version of Node.js ~45MB
FROM node:20.11.1-alpine3.18 as build

# info
ENV NODE_ENV=developement
WORKDIR /app

# update the system
RUN apk update && apk add openssl

# copy the source code
COPY . .
COPY ./.env.example.prod ./.env

# build the app
RUN npm i --ignore-scripts --frozen-lockfile
RUN npx prisma generate
RUN npm run build:node

# ------------------------------------------
# Host the build files
FROM node:20.11.1-alpine3.18 as runtime

# info
ENV NODE_ENV=production
ENV HOST=0.0.0.0
ENV PORT=80
EXPOSE 80/tcp
WORKDIR /app

# copy the build files
COPY --from=build /app .

CMD ["node", "build"]
