# https://bun.sh/guides/ecosystem/docker
# see all versions at https://hub.docker.com/r/oven/bun/tags
FROM oven/bun:1.0.31 as base

# update the system
RUN apt update && apt install openssl

WORKDIR /usr/src/app
COPY ./.env.example.prod ./.env

# -------------------------------------------------------------------------------------
# install dependencies into temp directory
# this will cache them and speed up future builds
FROM base AS install

ENV NODE_ENV=developement

RUN mkdir -p /temp/dev
WORKDIR /temp/dev

COPY package.json package-lock.json .
COPY prisma .
RUN bun pm migrate
# somehow needed, else `lockfile had changes, but lockfile is frozen`, errors if not installed previously...
RUN bun install --ignore-scripts
RUN bun install --ignore-scripts --frozen-lockfile
RUN bunx prisma generate

# -------------------------------------------------------------------------------------
# copy node_modules from temp directory
# then copy all (non-ignored) project files into the image
FROM base AS prerelease

ENV NODE_ENV=production
WORKDIR /usr/src/app

COPY --from=install /temp/dev/node_modules node_modules
COPY . .

# RUN bun test:unit, test:ui, test:integration
RUN bun run build:bun

# -------------------------------------------------------------------------------------
# copy source code into final image
FROM base AS release

COPY --from=install /temp/dev/node_modules node_modules
COPY --from=prerelease /usr/src/app/build .

# run the app
USER bun
ENV PORT=80
EXPOSE 80/tcp

ENTRYPOINT [ "bun", "run", "start" ]
