version: "3.8"

services:
    postgres:
        image: postgres:latest
        container_name: propromo-ts-postgres
        environment:
            POSTGRES_DB: propromo
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: propromo
        ports:
            - "54320:5432"
