name: Build - SvelteKit Website
on: ["push", "pull_request"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Node.js image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          file: Dockerfile.node.env
          push: true
          tags: |
            propromo/website-ts:node
            propromo/website-ts:latest
            ghcr.io/${{ github.repository_owner }}/propromo-website-ts:node
            ghcr.io/${{ github.repository_owner }}/propromo-website-ts:latest

      # NOT STABLE, sometimes builds and sometimes fails
      # - name: Build and push Bun.js image
      #  uses: docker/build-push-action@v5
      #  with:
      #    context: .
      #    platforms: linux/amd64
      #    file: Dockerfile.bun.env
      #    push: true
      #    tags: |
      #      propromo/website-ts:bun
      #      ghcr.io/${{ github.repository_owner }}/propromo-website-ts:bun
